---
- hosts: jvsc
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.git
    - geerlingguy.java
    - ansible-role-jenkins

- name: Config VM, Jenkins, Vault, Capistrano
  include: conf.yml
